@Restaurants.API_HostAddress = https://localhost:7127
@host = http://localhost
@port = 5029

//@RestaurantsAPI_HostAddress = {{host}}:{{port}}

GET {{Restaurants.API_HostAddress}}/api/restaurants
###

GET {{Restaurants.API_HostAddress}}/api/restaurants/30

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json
{
    "Name" : "Shittin on Shingelz 4",
    "Description": "A Last Resort",
    "Category": "MexicanZ",
    "HasDelivery": false,
    "ContactEmail": "info@shittin,com",
    "ContactPhoneNumber": "732-999-5593",
    "Street": "147 Water Treatement Boulevard",
    "City": "Sulphur Springs",
    "State": "NM",
    "PostalCode": "08889"
}

###
POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json
{
    "Name" : "Craptastier 2",
    "Description": "Mo' Poop 'n Pee",
    "Category": "Indian",
    "HasDelivery": false,
    "ContactEmail": "billy@soupy,net",
    "ContactPhoneNumber": "678-678-6788",
    "Street": "147 Water Treatement Boulevard",
    "City": "Sulphur Springs",
    "State": "NJ",
    "PostalCode": "62002-1234"
}

###
GET {{Restaurants.API_HostAddress}}/api/restaurants/{id}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/36

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/33
Content-Type: application/json
{
    "Name" : "Tonay's Spoonfullyullio???",
    "Description": "Soup to Nuts",
    "HasDelivery": true
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants

###
