@Restaurants.API_HostAddress = https://localhost:7127
@host = http://localhost
@port = 5029

//@RestaurantsAPI_HostAddress = {{host}}:{{port}}

GET {{Restaurants.API_HostAddress}}/api/restaurants
###

GET {{Restaurants.API_HostAddress}}/api/restaurants/31

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json
{
    "Name" : "Shittin on Shingelz 2",
    "Description": "A Last Resort",
    "Category": "Mexican",
    "HasDelivery": false,
    "ContactEmail": "info@shittin,com",
    "ContactPhoneNumber": "732-999-5593",
    "Street": "147 Water Treatement Boulevard",
    "City": "Sulphur Springs",
    "State": "NM",
    "PostalCode": "08889"
}

###
POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json
{
    "Name" : "Spoonfull",
    "Description": "Soups 'n Sammiches",
    "Category": "Winter Foods",
    "HasDelivery": false,
    "ContactEmail": "billy@soupy,net",
    "ContactPhoneNumber": "67",
    "Street": "147 Water Treatement Boulevard",
    "City": "Sulphur Springs",
    "State": "NJ",
    "PostalCode": "62002-1234"
}

###
GET {{Restaurants.API_HostAddress}}/api/restaurants/{id}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/999